CREATE TABLE [dbo].[UploadClaim] (
    [Id]                 INT            IDENTITY (1, 1) NOT NULL,
    [Policy]             NVARCHAR (MAX) NOT NULL,
    [Amount]             NVARCHAR (MAX) NOT NULL,
    [IssueDate]          NVARCHAR (MAX) NOT NULL,
    [ClaimType]          NVARCHAR (MAX) NOT NULL,
    [ServiceType]        NVARCHAR (MAX) NOT NULL,
    [DateOfIncident]     NVARCHAR (MAX) NOT NULL,
    [CauseOfLoss]        NVARCHAR (MAX) NOT NULL,
    [Reason]             NVARCHAR (MAX) NOT NULL,
    [Dept]               NVARCHAR (MAX) NOT NULL,
    [PDocument]          NVARCHAR (MAX) NULL,
    [Name]               NVARCHAR (MAX) NOT NULL,
    [CustomerType]       NVARCHAR (MAX) NOT NULL,
    [Gender]             NVARCHAR (MAX) NOT NULL,
    [CustomerDob]        NVARCHAR (MAX) NOT NULL,
    [Contact]            NVARCHAR (MAX) NOT NULL,
    [Education]          NVARCHAR (MAX) NOT NULL,
    [Occupation]         NVARCHAR (MAX) NOT NULL,
    [Income]             NVARCHAR (MAX) NOT NULL,
    [CAddress]           NVARCHAR (MAX) NOT NULL,
    [Pincode]            NVARCHAR (MAX) NOT NULL,
    [Comment]            NVARCHAR (MAX) NOT NULL,
    [CPhoto]             NVARCHAR (MAX) NULL,
    [BeneficiaryName]    NVARCHAR (MAX) NOT NULL,
    [Relation]           NVARCHAR (MAX) NOT NULL,
    [BeneficiaryDob]     NVARCHAR (MAX) NOT NULL,
    [BeneficiaryIncome]  NVARCHAR (MAX) NOT NULL,
    [BeneficiaryContact] NVARCHAR (MAX) NOT NULL,
    [BAddress]           NVARCHAR (MAX) NOT NULL,
    [BPincode]           NVARCHAR (MAX) NOT NULL,
    [BPhoto]             NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_UploadClaim] PRIMARY KEY CLUSTERED ([Id] ASC)
);

